name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: renovate-config.js
          token: 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