parameters:
  - name: checkmarxEnabled
    type: boolean
    default: true
  - name: deployEnabled
    type: boolean
    default: false
  - name: nexusIQEnabled
    type: boolean
    default: true
  - name: secretScannerEnabled
    type: boolean
    default: true
  - name: sonarqubeEnabled
    type: boolean
    default: true

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: 'Build'
        steps:
          - task: DownloadSecureFile@1
            displayName: 'Download Maven Settings'
            name: mvnsettings
            inputs:
              secureFile: mvn-settings.xml

          - script: |
              echo "Commenting out the Maven Central Related plugins"
              awk 'BEGIN{p=0}/<plugin>/{p=1;buf=$0;next}/<\/plugin>/{buf=buf"\n"$0;if(p&&buf~/<groupId>org\.sonatype\.central<\/groupId>/&&buf~/<artifactId>central-publishing-maven-plugin<\/artifactId>/){print "<!--\n"buf"\n-->"}else{print buf};p=0;next}{if(p){buf=buf"\n"$0}else{print}}' pom.xml > pom.tmp && mv pom.tmp pom.xml
              awk 'BEGIN{p=0}/<plugin>/{p=1;buf=$0;next}/<\/plugin>/{buf=buf"\n"$0;if(p&&buf~/<groupId>org\.apache\.maven\.plugins<\/groupId>/&&buf~/<artifactId>maven-gpg-plugin<\/artifactId>/){print "<!--\n"buf"\n-->"}else{print buf};p=0;next}{if(p){buf=buf"\n"$0}else{print}}' pom.xml > pom.tmp && mv pom.tmp pom.xml
            displayName: 'Comment Out Maven Central Related plugins'

          - script: |
              echo "Replacing distributionManagement block"
              awk '
                BEGIN {inblock=0}
                /<distributionManagement>/ {inblock=1; print "  <distributionManagement>\n    <repository>\n      <id>releases</id>\n      <name>IP Releases</name>\n      <url>$(NEXUS_DIST_MANAGEMENT_RELEASES)</url>\n    </repository>\n    <snapshotRepository>\n      <id>snapshot</id>\n      <name>IP Snapshots</name>\n      <url>$(NEXUS_DIST_MANAGEMENT_SNAPSHOTS)</url>\n    </snapshotRepository>\n  </distributionManagement>"; next}
                /<\/distributionManagement>/ {inblock=0; next}
                {if(!inblock) print}
              ' pom.xml > pom.tmp && mv pom.tmp pom.xml
            displayName: 'Replace Distribution Management'

          - task: Maven@4
            displayName: Maven Build
            inputs:
              effectivePomSkip: false
              goals: 'clean verify'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              mavenAuthenticateFeed: false
              mavenOptions: '-Xmx3072m'
              mavenPomFile: 'pom.xml'
              mavenVersionOption: 'Default'
              publishJUnitResults: true
              sonarQubeRunAnalysis: false
              testResultsFiles: '**/surefire-reports/TEST-*.xml'

          - ${{ if parameters.sonarqubeEnabled }}:
            - task: RabobankCQSTask@1
              displayName: SonarQube Analysis
              inputs:
                mainSonarQubeProject: 'rabobank.shadow-tool-92651-rw'
                qualityGateBreak: false
                scannerMode: 'maven'
                sqServiceConnection: 'Rabobank CQS Service Connection - TEST'

          - ${{ if parameters.deployEnabled }}:
            - task: Maven@4
              displayName: Deploy
              inputs:
                effectivePomSkip: false
                goals: 'clean deploy'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.17'
                mavenAuthenticateFeed: false
                mavenOptions: '-Xmx3072m -Daether.dependencyCollector.impl=bf -Daether.dependencyCollector.bf.threads=10 -Daether.dependencyCollector.pool.artifact=hard -Daether.dependencyCollector.pool.dependency=hard'
                mavenPomFile: 'pom.xml'
                mavenVersionOption: 'Default'
                options: '-B -s $(mvnsettings.secureFilePath) -ntp'
                publishJUnitResults: false
                sonarQubeRunAnalysis: false

      - job: Checkmarx
        condition: and(succeeded(), eq('${{ parameters.checkmarxEnabled }}', true))
        displayName: Rabobank Checkmarx Scan
        pool: Shared-EU-Container-Linux-Compliancy-S-Prod
        steps:
          - task: Rabobank Checkmarx@2
            inputs:
              CheckmarxService: 'Checkmarx-MSC'
              mainCheckmarxProject: 'rabobank.shadow-tool-92651-rw'

      - job:
        condition: and(succeeded(), eq('${{ parameters.secretScannerEnabled }}', true))
        displayName: Rabobank Secret Scanner
        pool: Shared-EU-Container-Linux-Compliancy-S-Prod
        steps:
          - task: secret-scanning-task@0

      - job: NexusIQ
        condition: and(succeeded(), eq('${{ parameters.nexusIQEnabled }}', true))
        displayName: Nexus IQ Scan
        steps:
          - task: JavaToolInstaller@0
            displayName: "Use Java 17"
            inputs:
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled
              versionSpec: 17

          - task: Maven@4
            displayName: 'MavenNexusIQ'
            inputs:
              effectivePomSkip: false
              goals: 'com.sonatype.clm:clm-maven-plugin:index'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              mavenAuthenticateFeed: false
              mavenPomFile: 'pom.xml'
              mavenVersionOption: 'Default'
              publishJUnitResults: false
              sonarQubeRunAnalysis: false

          - task: NexusIqPipelineTask@1
            displayName: 'SonatypeEvaluate'
            inputs:
              applicationId: 'shadow-tool'
              nexusIqService: 'Rabobank SCA NexusIQ'
              scanTargets: "**/module.xml"
              stage: 'Build'
