trigger:
  branches:
    include:
      - '*'
    exclude:
      - main

pool:
  name: 'Shared-EU-VM-Linux-Legacy-M-Prod'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
