pr:
  branches:
    include:
      - '*'
    exclude:
      - main
      - release/*

variables:
  - group: secure-vars

pool:
  name: 'Shared-EU-VM-Linux-Legacy-M-Prod'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: 'Build and Deploy snapshot'
        steps:
            - task: DownloadSecureFile@1
              displayName: 'Download Maven Settings'
              name: mvnsettings
              inputs:
                secureFile: mvn-settings.xml

            - script: |
                echo "Commenting out the Maven Central Related plugins"
                awk 'BEGIN{p=0}/<plugin>/{p=1;buf=$0;next}/<\/plugin>/{buf=buf"\n"$0;if(p&&buf~/<groupId>org\.sonatype\.central<\/groupId>/&&buf~/<artifactId>central-publishing-maven-plugin<\/artifactId>/){print "<!--\n"buf"\n-->"}else{print buf};p=0;next}{if(p){buf=buf"\n"$0}else{print}}' pom.xml > pom.tmp && mv pom.tmp pom.xml
                awk 'BEGIN{p=0}/<plugin>/{p=1;buf=$0;next}/<\/plugin>/{buf=buf"\n"$0;if(p&&buf~/<groupId>org\.apache\.maven\.plugins</groupId>/&&buf~/<artifactId>maven-gpg-plugin</artifactId>/){print "<!--\n"buf"\n-->"}else{print buf};p=0;next}{if(p){buf=buf"\n"$0}else{print}}' pom.xml > pom.tmp && mv pom.tmp pom.xml
              displayName: 'Comment Out Maven Central Related plugins'

            - script: |
                echo "Replacing distributionManagement block"
                awk '
                  BEGIN {inblock=0}
                  /<distributionManagement>/ {inblock=1; print "  <distributionManagement>\n    <repository>\n      <id>releases</id>\n      <name>IP Releases</name>\n      <url>$(NEXUS_DIST_MANAGEMENT_RELEASES)</url>\n    </repository>\n    <snapshotRepository>\n      <id>snapshot</id>\n      <name>IP Snapshots</name>\n      <url>$(NEXUS_DIST_MANAGEMENT_SNAPSHOTS)</url>\n    </snapshotRepository>\n  </distributionManagement>"; next}
                  /<\/distributionManagement>/ {inblock=0; next}
                  {if(!inblock) print}
                ' pom.xml > pom.tmp && mv pom.tmp pom.xml
              displayName: 'Replace Distribution Management'

            - task: Maven@4
              displayName: Maven Build
              inputs:
                mavenOptions: '-Xmx3072m'
                mavenPomFile: 'pom.xml'
                goals: 'clean verify'
                jdkVersionOption: '1.17'

            - task: Maven@4
              displayName: Deploy Snapshot
              inputs:
                mavenPomFile: 'pom.xml'
                goals: 'clean deploy'
                options: '-B -s $(mvnsettings.secureFilePath) -ntp'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.17'
                mavenOptions: '-Xmx3072m -Daether.dependencyCollector.impl=bf -Daether.dependencyCollector.bf.threads=10 -Daether.dependencyCollector.pool.artifact=hard -Daether.dependencyCollector.pool.dependency=hard '
                mavenAuthenticateFeed: false
                effectivePomSkip: false
                sonarQubeRunAnalysis: false

      - job: Checkmarx
        displayName: Rabobank Checkmarx Scan
        pool: Shared-EU-Container-Linux-Compliancy-S-Prod
        steps:
          - task: Rabobank Checkmarx@2
            inputs:
              CheckmarxService: 'Checkmarx-MSC'
              mainCheckmarxProject: 'rabobank.shadow-tool-92651-rw'

      - job:
        displayName: Rabobank Secret Scanner
        pool: Shared-EU-Container-Linux-Compliancy-S-Prod
        steps:
          - task: secret-scanning-task@0

      - job: NexusIQ
        displayName: Nexus IQ Scan
        steps:
          - task: JavaToolInstaller@0
            displayName: "Use Java 17"
            inputs:
              versionSpec: 17
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled

          - task: Maven@4
            displayName: 'MavenNexusIQ'
            inputs:
              goals: 'com.sonatype.clm:clm-maven-plugin:index'
              jdkVersion: '17'

          - task: NexusIqPipelineTask@1
            displayName: 'SonatypeEvaluate'
            inputs:
              nexusIqService: 'Rabobank SCA NexusIQ' # Name of default service connection
              applicationId: 'CF-Metrics-Exporter' # REPLACE with applicationId Name of the application in NexusIQ, by default same name as pipeline
              stage: 'Build'
              scanTargets: "**/module.xml"
