trigger:
  tags:
    include:
      - '*'

variables:
  - group: secure-vars

pool:
  name: 'Shared-EU-VM-Linux-Legacy-M-Prod'

stages:
  - template: /.azure/templates/build.yml
    parameters:
      checkmarxEnabled: true
      deployEnabled: true
      secretScannerEnabled: true
      sonarqubeEnabled: true
