# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

name: Major Release

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - id: CD
        uses: ./.github/workflows/actions/cd
        with:
          new-version: '\${parsedVersion.majorVersion}.0.0'
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-token: ${{ secrets.MAVEN_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-push-pat: ${{ secrets.VERSION_PUSH_PAT }}
          bot-mail: ${{ secrets.BOT_MAIL }}
