name: Major Release

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.0
      - id: CD
        uses: ./.github/workflows/actions/cd
        with:
          new-version: '\${parsedVersion.nextMajorVersion}.0.0'
